export const AUTH_SERVICE = 'AUTH_SERVICE';
export const EVENT_SERVICE = 'EVENT_SERVICE';
export const NOTIFICATION_SERVICE = 'NOTIFICATION_SERVICE';
export const TICKET_SERVICE = 'TICKET_SERVICE';
export const REPORT_SERVICE = 'REPORT_SERVICE';
export const FILE_SERVICE = 'FILE_SERVICE';