// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.5.1
//   protoc               v3.20.3
// source: proto/event.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "event";

export interface Empty {
}

export interface UpdateCategoryRequest {
  id: string;
  name?: string | undefined;
  description?: string | undefined;
}

export interface CreateCategoryRequest {
  name: string;
  description?: string | undefined;
}

export interface CategoryByIdRequest {
  id: string;
}

export interface EventByIdRequest {
  id: string;
}

export interface AllCategoryResponse {
  categories: Category[];
}

export interface EventResponse {
  event: EventType | undefined;
}

export interface AllEventResponse {
  events: EventType[];
}

export interface CategoryResponse {
  category: Category | undefined;
}

export interface Category {
  id: string;
  name: string;
  description: string;
}

export interface CreateEventRequest {
  name: string;
  description: string;
  startDate: string;
  endDate: string;
  location: string;
  speaker: string[];
  guest: string[];
  categoryId: string;
  isFree: boolean;
  price: number;
  maxParticipants: number;
  banner: string;
  videoIntro: string;
  otherDocument: string[];
  createdBy: string;
}

export interface UpdateEventRequest {
  id: string;
  name?: string | undefined;
  description?: string | undefined;
  startDate?: string | undefined;
  endDate?: string | undefined;
  location?: string | undefined;
  speaker: string[];
  guest: string[];
  categoryId?: string | undefined;
  isFree?: boolean | undefined;
  price?: number | undefined;
  maxParticipants?: number | undefined;
  banner?: string | undefined;
  videoIntro?: string | undefined;
  otherDocument: string[];
  status?: string | undefined;
}

export interface EventType {
  id: string;
  name: string;
  description: string;
  startDate: string;
  endDate: string;
  location: string;
  speaker: string[];
  guest: string[];
  categoryId: string;
  isFree: boolean;
  price: number;
  maxParticipants: number;
  banner: string;
  videoIntro: string;
  otherDocument: string[];
  status: string;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
}

export const EVENT_PACKAGE_NAME = "event";

export interface EventServiceClient {
  getAllEvent(request: Empty): Observable<AllEventResponse>;

  getEventById(request: EventByIdRequest): Observable<EventResponse>;

  getCategoryById(request: CategoryByIdRequest): Observable<CategoryResponse>;

  getAllCategory(request: Empty): Observable<AllCategoryResponse>;

  createEvent(request: CreateEventRequest): Observable<EventResponse>;

  createCategory(request: CreateCategoryRequest): Observable<CategoryResponse>;

  updateEvent(request: UpdateEventRequest): Observable<EventResponse>;

  updateCategory(request: UpdateCategoryRequest): Observable<CategoryResponse>;
}

export interface EventServiceController {
  getAllEvent(request: Empty): Promise<AllEventResponse> | Observable<AllEventResponse> | AllEventResponse;

  getEventById(request: EventByIdRequest): Promise<EventResponse> | Observable<EventResponse> | EventResponse;

  getCategoryById(
    request: CategoryByIdRequest,
  ): Promise<CategoryResponse> | Observable<CategoryResponse> | CategoryResponse;

  getAllCategory(request: Empty): Promise<AllCategoryResponse> | Observable<AllCategoryResponse> | AllCategoryResponse;

  createEvent(request: CreateEventRequest): Promise<EventResponse> | Observable<EventResponse> | EventResponse;

  createCategory(
    request: CreateCategoryRequest,
  ): Promise<CategoryResponse> | Observable<CategoryResponse> | CategoryResponse;

  updateEvent(request: UpdateEventRequest): Promise<EventResponse> | Observable<EventResponse> | EventResponse;

  updateCategory(
    request: UpdateCategoryRequest,
  ): Promise<CategoryResponse> | Observable<CategoryResponse> | CategoryResponse;
}

export function EventServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getAllEvent",
      "getEventById",
      "getCategoryById",
      "getAllCategory",
      "createEvent",
      "createCategory",
      "updateEvent",
      "updateCategory",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("EventService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("EventService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const EVENT_SERVICE_NAME = "EventService";
