// src\App.tsx
// src/App.tsx
import { RouterProvider } from 'react-router-dom';
import { ConfigProvider, theme as antdTheme, Spin } from 'antd';

import { HelmetProvider } from 'react-helmet-async';
import { StylesContext } from './context';
import routes from './routes/routes.tsx';
import { useSelector, useDispatch } from 'react-redux';
import { RootState } from './redux/store.ts';
import './App.css';
import { useEffect, useState } from 'react'; // Import useState
import { setUser } from './redux/userSlice.tsx';
import axiosInstance from './api/axiosInstance'; // Import axiosInstance

// color palettes: triadic #A1A7CB, #CBA1A7, #A7CBA1
// 10 color objects of primary #2378c3 as generated by https://smart-swatch.netlify.app/#2378c3
// This is for reference purposes

const COLOR = {
  50: '#e0f1ff',
  100: '#b0d2ff',
  200: '#7fb0ff',
  300: '#4d8bff',
  400: '#1e79fe',
  500: '#076ee5',
  600: '#0062b3',
  700: '#004f81',
  800: '#003650',
  900: '#001620',
  borderColor: '#E7EAF3B2',
};

function App() {
  const { mytheme } = useSelector((state: RootState) => state.theme);
  const dispatch = useDispatch();
  const [isAuthLoading, setIsAuthLoading] = useState(true); // **[ADDED]** State to track authentication loading

  useEffect(() => {
    const accessTokenFromUrl = new URLSearchParams(window.location.search).get('accessToken');
    let accessToken = localStorage.getItem('accessToken');

    if (accessTokenFromUrl) {
      accessToken = accessTokenFromUrl;
      localStorage.setItem('accessToken', accessToken);
      window.history.replaceState({}, document.title, '/dashboards/general');
    }

    if (accessToken) {
      const fetchUserInfo = async () => {
        try {
          const response = await axiosInstance.get('/users/profile'); // Call /users/profile API
          const userProfile = (response.data as { data: { user: any } }).data.user; // Assuming the API returns user data in response.data.data.user
          dispatch(setUser(userProfile)); // Dispatch user info to Redux store
          localStorage.setItem('user', JSON.stringify(userProfile)); // Update local storage
        } catch (error) {
          console.error('Failed to fetch user profile:', error);
          localStorage.removeItem('user'); // Optionally remove user from local storage if fetch fails
        } finally {
          setIsAuthLoading(false); // **[ADDED]** Set loading to false after fetch (success or fail)
        }
      };

      fetchUserInfo(); // Call fetchUserInfo after getting accessToken
    } else {
      localStorage.removeItem('user');
      setIsAuthLoading(false); // **[ADDED]** Set loading to false if no accessToken
    }
  }, [dispatch]);

  return (
    <HelmetProvider>
      <ConfigProvider
        theme={{
          token: {
            colorPrimary: COLOR['500'],
            borderRadius: 6,
            fontFamily: 'Lato, sans-serif',
          },
          components: {
            Breadcrumb: {},
            Button: {
              colorLink: COLOR['500'],
              colorLinkActive: COLOR['700'],
              colorLinkHover: COLOR['300'],
            },
            Calendar: {
              colorBgContainer: 'none',
            },
            Card: {
              colorBorderSecondary: COLOR['borderColor'],
            },
            Carousel: {
              colorBgContainer: COLOR['800'],
              dotWidth: 8,
            },
            Rate: {
              colorFillContent: COLOR['100'],
              colorText: COLOR['600'],
            },
            Segmented: {
              colorBgLayout: COLOR['100'],
              borderRadius: 6,
              colorTextLabel: '#000000',
            },
            Table: {
              borderColor: COLOR['100'],
              colorBgContainer: 'none',
              headerBg: 'none',
              rowHoverBg: COLOR['50'],
            },
            Tabs: {
              colorBorderSecondary: COLOR['100'],
            },
            Timeline: {
              dotBg: 'none',
            },
            Typography: {
              colorLink: COLOR['500'],
              colorLinkActive: COLOR['700'],
              colorLinkHover: COLOR['300'],
              linkHoverDecoration: 'underline',
            },
          },
          algorithm:
            mytheme === 'dark'
              ? antdTheme.darkAlgorithm
              : antdTheme.defaultAlgorithm,
        }}
      >
        <StylesContext.Provider
          value={{
            rowProps: {
              gutter: [
                { xs: 8, sm: 16, md: 24, lg: 32 },
                { xs: 8, sm: 16, md: 24, lg: 32 },
              ],
            },
            carouselProps: {
              autoplay: true,
              dots: true,
              dotPosition: 'bottom',
              infinite: true,
              slidesToShow: 3,
              slidesToScroll: 1,
            },
          }}
        >
          {isAuthLoading ? ( // **[ADDED]** Conditional rendering based on isAuthLoading
            <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh' }}>
              <Spin size="large" tip="Loading..." />
            </div>
          ) : (
            <RouterProvider router={routes} /> // Render RouterProvider when not loading
          )}
        </StylesContext.Provider>
      </ConfigProvider>
    </HelmetProvider>
  );
}

export default App;
export {COLOR}
